// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Get the storage key for the auth token
const getAuthTokenKey = () => 'sb-' + SUPABASE_URL.split('://')[1] + '-auth-token';

// Helper to clear session and dispatch error event
const handleSessionExpired = (message = 'Session expired. Please log in again.') => {
  console.warn('Session expired, clearing local storage...');

  // Clear the stored session
  localStorage.removeItem(getAuthTokenKey());

  // Dispatch custom event for the app to handle
  window.dispatchEvent(new CustomEvent('supabase:auth:error', {
    detail: { message }
  }));
};

// Check and validate stored session on startup
const validateStoredSession = async () => {
  const tokenKey = getAuthTokenKey();
  const storedData = localStorage.getItem(tokenKey);

  if (storedData) {
    try {
      const parsed = JSON.parse(storedData);
      // Check if the refresh_token exists and is not expired
      if (parsed?.refresh_token) {
        // Session exists, let Supabase handle the validation
        console.log('Found stored session, will validate on next request');
      } else {
        // No refresh token, clear the session
        console.log('No refresh token found in stored session, clearing...');
        localStorage.removeItem(tokenKey);
      }
    } catch (e) {
      // Invalid JSON stored, clear it
      console.warn('Invalid session data in storage, clearing...');
      localStorage.removeItem(tokenKey);
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Initialize validation on module load
validateStoredSession();

// Listen for auth events and handle token refresh errors
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Auth state change:', event, session ? 'session exists' : 'no session');

  if (event === 'TOKEN_REFRESHED') {
    console.log('Session refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('User signed out');
    localStorage.removeItem(getAuthTokenKey());
  } else if (event === 'USER_UPDATED') {
    console.log('User updated');
  } else if (event === 'INITIAL_SESSION') {
    console.log('Initial session check');
    if (!session) {
      console.log('No valid session found');
      localStorage.removeItem(getAuthTokenKey());
    }
  }
});

// Helper function to sign out and clear all tokens
export const clearSession = async () => {
  await supabase.auth.signOut();
  localStorage.removeItem(getAuthTokenKey());
};

// Helper to manually check if session is valid and refresh if needed
export const refreshSession = async () => {
  try {
    const { data, error } = await supabase.auth.refreshSession();
    if (error) {
      handleSessionExpired('Failed to refresh session. Please log in again.');
      return null;
    }
    return data.session;
  } catch (error: unknown) {
    const err = error as AuthError;
    if (err.message?.includes('Invalid Refresh Token') ||
      err.message?.includes('Refresh Token Not Found')) {
      handleSessionExpired('Your session has expired. Please log in again.');
    }
    return null;
  }
};